-- MESSAGE_TYPE 컬럼 크기 수정
USE umate_db;

-- 기존 테이블 구조 확인
DESCRIBE CHAT_HISTORY;

-- MESSAGE_TYPE 컬럼 크기를 늘림
ALTER TABLE CHAT_HISTORY MODIFY COLUMN MESSAGE_TYPE VARCHAR(50) NOT NULL;

-- 수정된 구조 확인
DESCRIBE CHAT_HISTORY;

-- 기존 데이터 확인
SELECT * FROM CHAT_HISTORY LIMIT 10; 