-- 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS umate_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE umate_db;

-- 사용자 테이블
CREATE TABLE IF NOT EXISTS USER (
    EMAIL VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(100),
    GENDER VARCHAR(10),
    BIRTHDAY DATE,
    PHONE_PLAN VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 채팅 히스토리 테이블
CREATE TABLE IF NOT EXISTS CHAT_HISTORY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255),
    MESSAGE_TYPE VARCHAR(20) NOT NULL,
    MESSAGE TEXT NOT NULL,
    AUDIO_DATA LONGBLOB,
    CONTEXT_INFO TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_email_created (EMAIL, CREATED_AT),
    FOREIGN KEY (EMAIL) REFERENCES USER(EMAIL) ON DELETE CASCADE
);

-- 테스트 사용자 데이터 삽입
INSERT IGNORE INTO USER (EMAIL, NAME, GENDER, BIRTHDAY, PHONE_PLAN) VALUES 
('test@example.com', '테스트 사용자', '남성', '1990-01-01', 'Basic Plan'),
('test@test.com', 'Test User', '여성', '1995-05-15', 'Premium Plan');

-- 권한 확인 (필요시)
-- GRANT ALL PRIVILEGES ON umate_db.* TO 'root'@'localhost';
-- FLUSH PRIVILEGES; 